[package]
name = "extended-syntax"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
reqwest = { version = "0.11", features = ["blocking"] }

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
